Minhasmembranas
gepac/gepac.github.io pull request #13
Opened 2019-08-17 21:37 UTC by alexprestes

2019-08-17 22:52 UTC, heitorPB requested changes
Só conferi as seções do Markdown. Tem alguns pequenos ajustes para fazer.

2019-08-17 22:52 UTC, heitorPB commented on _posts/2019-08-21-projeto-membranas.md
> +# Solução numérica para ondas estacionárias em membranas
Deveria ser `##` no lugar de `#`

2019-08-17 22:52 UTC, heitorPB commented on _posts/2019-08-21-projeto-membranas.md
> +#### Bibliotecas usadas
Acho que aqui e em todos os `####` deveria ser `###`, ou não?

2019-08-17 23:54 UTC, AlexPrestes reviewed
Alterações sugeridas pelo heitor

2019-08-20 16:19 UTC, LFRusso commented
Top

2019-08-21 00:57 UTC, heitorPB approved these changes

2019-08-21 00:58 UTC, merged