Primeira aula de bibliotecas
gepac/gepac.github.io pull request #7
Opened 2019-05-16 21:11 UTC by solano

Acredito que esteja pronta. A parte de matplotlib é nova e ainda não foi revisada.

2019-05-16 22:26 UTC, heitorPB requested changes

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +sequência de cinco números, um array de formato `(5,3)` é uma matriz $$5
`(5,3)` -> `(5, 3)`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +\times 3$$, e um de formato `(3,3,3)` é um ''cubo'' de 27 números (que pode
`(3,3,3)` -> `(3, 3, 3)`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +    plt.plot(x, y, formato)
Precisa indentação aqui?

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +de bolinha, quadrado ou triângulo). O parâmetro `formato` é **opcional**, e
`**opcional**` -> `*opcional*`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +O primeiro passo é gerar os valores de $$x$$ que serão usados; aqui, usamos
$$x$$ -> \`x\`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +a função `linspace`. Em seguida plotamos as funções com a função `plot` e
`plotamos as funções` -> `graficamos as funções`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +plt.plot(x, 1/x**2)
`plt.plot(x, 1 / x**2)`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +tx = np.linspace(0,10.5,100)
`tx = np.linspace(0, 10.5, 100)`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +ty = 5 * np.sin(tx/7)
ty = 5 * np.sin(tx / 7)

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +1. Calcule $$\exp(\cos(n))$$ para todos os inteiros $$n$$ de -10 até 10.
$$n$$ -> \`n\`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +1. Use a função `savetxt` para escrever uma tabela com 100 valores de $$x$$
`savetxt` -> `savetxt()`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +   e $$e^x$$, com $$x$$ variando entre 0 e 1.
$$x$$ -> \`x\`

2019-05-16 22:26 UTC, heitorPB commented on _posts/2019-05-17-oficina-scipy-aula1.md
> +   função `loadtxt`. Usando *slicing*, faça um array contendo apenas a
`loadtxt` -> `loadtxt()`

2019-05-17 01:44 UTC, heitorPB commented on _layouts/base.html
> +common-ext-js:
essas duas linhas ja estao na master, se puder remover facilita o futuro.

2019-05-17 12:19 UTC, solano commented
Tudo revisado e squashado. Também adicionei uma licença. Só preciso da aprovação de alguém pra dar merge.

2019-05-17 12:45 UTC, heitorPB approved these changes

2019-05-17 12:46 UTC, merged